site_name: Cryptomator
site_url: https://docs.cryptomator.org
site_description: FLOSS Cloud Encryption.
site_author: Cryptomator Team
repo_url: https://github.com/cryptomator/docs/
theme: readthedocs
strict: true
copyright: Copyright &copy; 2019 <a href="https://cryptomator.org/impressum">Skymatic GmbH</a> and <a href="https://github.com/cryptomator/docs/graphs/contributors">contributers</a>.
markdown_extensions:
  - smarty
  - attr_list
  - admonition
  - toc:
      permalink: True
plugins:
  - search:
      lang: en
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Desktop Application:
    - Setup: desktop/setup.md
    - Vault Management: desktop/vault-management.md
    - Accessing a Vault: desktop/access-vault.md
  - Android App:
    - Setup: android/setup.md
  - iOS App:
    - Setup: ios/setup.md
  - Contributing:
    - Introduction: contributing/introduction.md
