site_name: Cryptomator
site_url: https://docs.cryptomator.org
repo_url: https://github.com/cryptomator/docs/
theme: readthedocs
strict: true
nav:
  - Home: index.md
  - Getting Started:
    - Setup: setup.md
    - Vault Management: vault-management.md
    - Accessing a Vault: access-vault.md
