site_name: Cryptomator
site_url: https://docs.cryptomator.org
site_description: FLOSS Cloud Encryption.
site_author: Cryptomator Team
repo_url: https://github.com/cryptomator/docs/
theme: readthedocs
strict: true
copyright: Copyright &copy; 2019 <a href="https://cryptomator.org/impressum">Skymatic GmbH</a> and <a href="https://github.com/cryptomator/docs/graphs/contributors">contributors</a>.
markdown_extensions:
  - smarty
  - attr_list
  - admonition
  - toc:
      permalink: True
plugins:
  - search:
      lang: en
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
nav:
  - Home: index.md
  - Contribute: contribute.md
  - Security:
    - Advice: security/advice.md
    - Architecture: security/architecture.md
  - Desktop Application:
    - Setup: desktop/setup.md
    - Vault Management: desktop/vault-management.md
    - Accessing a Vault: desktop/access-vault.md
  - Android App:
    - Setup: android/setup.md
  - iOS App:
    - Setup: ios/setup.md
    - Vault Management: ios/vault-management.md
  - Sanitizer:
    - Introduction: sanitizer/introduction.md
    - Setup: sanitizer/setup.md
    - Usage: sanitizer/usage.md 
